SELECT TOP (10) [order_id]
      ,[order_status]
      ,[customer]
      ,[order_date]
      ,[order_quantity]
      ,[sales]
      ,[discount]
      ,[discount_value]
      ,[product_category]
      ,[product_sub_category]
  FROM [Sales Performance Report].[dbo].[dqlab_sales_store]